{{- if include "trove.hasManagedSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trove.secretName" . }}
  labels:
    {{- include "trove.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.database.url (not .Values.database.existingSecret.name) }}
  TROVE_DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.devToken (not .Values.auth.devTokenExistingSecret.name) }}
  TROVE_AUTH_DEV_TOKEN: {{ .Values.auth.devToken | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oidc.clientSecret (not .Values.oidc.clientSecretExistingSecret.name) }}
  TROVE_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
