// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_path.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPackageMaintainer = `-- name: AddPackageMaintainer :one
insert into package_maintainers (id, package_id, user_id, role, created_at)
values ($1, $2, $3, $4, now())
returning id, package_id, user_id, role, created_at
`

type AddPackageMaintainerParams struct {
	ID        pgtype.UUID `json:"id"`
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

type AddPackageMaintainerRow struct {
	ID        pgtype.UUID        `json:"id"`
	PackageID pgtype.UUID        `json:"package_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddPackageMaintainer(ctx context.Context, arg AddPackageMaintainerParams) (AddPackageMaintainerRow, error) {
	row := q.db.QueryRow(ctx, addPackageMaintainer,
		arg.ID,
		arg.PackageID,
		arg.UserID,
		arg.Role,
	)
	var i AddPackageMaintainerRow
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const addReviewComment = `-- name: AddReviewComment :one
insert into review_comments (id, review_id, author_id, body, created_at)
values ($1, $2, $3, $4, now())
returning id, review_id, author_id, body, created_at
`

type AddReviewCommentParams struct {
	ID       pgtype.UUID `json:"id"`
	ReviewID pgtype.UUID `json:"review_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) AddReviewComment(ctx context.Context, arg AddReviewCommentParams) (ReviewComment, error) {
	row := q.db.QueryRow(ctx, addReviewComment,
		arg.ID,
		arg.ReviewID,
		arg.AuthorID,
		arg.Body,
	)
	var i ReviewComment
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const countApprovalsForVersion = `-- name: CountApprovalsForVersion :one
select count(*) as approval_count
from approvals
where package_version_id = $1
`

func (q *Queries) CountApprovalsForVersion(ctx context.Context, packageVersionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalsForVersion, packageVersionID)
	var approval_count int64
	err := row.Scan(&approval_count)
	return approval_count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
insert into api_tokens (id, token_hash, display_name, actor_user_id, actor_service_account, scopes,
                        org_id, namespace_id, package_id, created_at, expires_at)
values ($1, $2, $3, $4,
        $5, $6::text[], $7,
        $8, $9, now(), $10)
returning id, token_hash, display_name, actor_user_id, actor_service_account, scopes,
          org_id, namespace_id, package_id, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID                  pgtype.UUID        `json:"id"`
	TokenHash           string             `json:"token_hash"`
	DisplayName         string             `json:"display_name"`
	ActorUserID         pgtype.UUID        `json:"actor_user_id"`
	ActorServiceAccount pgtype.Text        `json:"actor_service_account"`
	Scopes              []string           `json:"scopes"`
	OrgID               pgtype.UUID        `json:"org_id"`
	NamespaceID         pgtype.UUID        `json:"namespace_id"`
	PackageID           pgtype.UUID        `json:"package_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.TokenHash,
		arg.DisplayName,
		arg.ActorUserID,
		arg.ActorServiceAccount,
		arg.Scopes,
		arg.OrgID,
		arg.NamespaceID,
		arg.PackageID,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DisplayName,
		&i.ActorUserID,
		&i.ActorServiceAccount,
		&i.Scopes,
		&i.OrgID,
		&i.NamespaceID,
		&i.PackageID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
with created_review as (
  insert into reviews (id, package_version_id, reviewer_id, status, comment, created_at, updated_at)
  select $1, $2, $3, $4,
         $5, now(), now()
  where exists (
    select 1 from package_versions
    where id = $2
      and lifecycle in ('draft', 'review')
  )
  returning id, package_version_id, reviewer_id, status, comment, created_at, updated_at
), updated_version as (
  update package_versions
  set lifecycle = 'review', updated_at = now()
  where id = $2
    and lifecycle = 'draft'
    and exists (select 1 from created_review)
  returning id
)
select id, package_version_id, reviewer_id, status, comment, created_at, updated_at
from created_review
`

type CreateReviewParams struct {
	ID               pgtype.UUID `json:"id"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	Status           string      `json:"status"`
	Comment          pgtype.Text `json:"comment"`
}

type CreateReviewRow struct {
	ID               pgtype.UUID        `json:"id"`
	PackageVersionID pgtype.UUID        `json:"package_version_id"`
	ReviewerID       pgtype.UUID        `json:"reviewer_id"`
	Status           string             `json:"status"`
	Comment          pgtype.Text        `json:"comment"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.PackageVersionID,
		arg.ReviewerID,
		arg.Status,
		arg.Comment,
	)
	var i CreateReviewRow
	err := row.Scan(
		&i.ID,
		&i.PackageVersionID,
		&i.ReviewerID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (id, email, display_name, oidc_issuer, oidc_subject, created_at, updated_at)
values ($1, $2, $3, $4, $5, now(), now())
returning id, email, display_name, avatar_url, oidc_issuer, oidc_subject, created_at, updated_at
`

type CreateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	OidcIssuer  pgtype.Text `json:"oidc_issuer"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.OidcIssuer,
		arg.OidcSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePackageMaintainer = `-- name: EnsurePackageMaintainer :exec
insert into package_maintainers (id, package_id, user_id, role, created_at)
values ($1, $2, $3, $4, now())
on conflict (package_id, user_id) do nothing
`

type EnsurePackageMaintainerParams struct {
	ID        pgtype.UUID `json:"id"`
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) EnsurePackageMaintainer(ctx context.Context, arg EnsurePackageMaintainerParams) error {
	_, err := q.db.Exec(ctx, ensurePackageMaintainer,
		arg.ID,
		arg.PackageID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
select id, token_hash, display_name, actor_user_id, actor_service_account, scopes,
       org_id, namespace_id, package_id, created_at, expires_at, last_used_at, revoked_at
from api_tokens
where token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DisplayName,
		&i.ActorUserID,
		&i.ActorServiceAccount,
		&i.Scopes,
		&i.OrgID,
		&i.NamespaceID,
		&i.PackageID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPackageVisibility = `-- name: GetPackageVisibility :one
select p.visibility
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
`

type GetPackageVisibilityParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

func (q *Queries) GetPackageVisibility(ctx context.Context, arg GetPackageVisibilityParams) (string, error) {
	row := q.db.QueryRow(ctx, getPackageVisibility, arg.Org, arg.Namespace, arg.PackageName)
	var visibility string
	err := row.Scan(&visibility)
	return visibility, err
}

const getReview = `-- name: GetReview :one
select id, package_version_id, reviewer_id, status, comment, created_at, updated_at
from reviews
where id = $1
`

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PackageVersionID,
		&i.ReviewerID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, avatar_url, oidc_issuer, oidc_subject, created_at, updated_at
from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, display_name, avatar_url, oidc_issuer, oidc_subject, created_at, updated_at
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDC = `-- name: GetUserByOIDC :one
select id, email, display_name, avatar_url, oidc_issuer, oidc_subject, created_at, updated_at
from users
where oidc_issuer = $1
  and oidc_subject = $2
`

type GetUserByOIDCParams struct {
	OidcIssuer  pgtype.Text `json:"oidc_issuer"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDC, arg.OidcIssuer, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasApprovalFrom = `-- name: HasApprovalFrom :one
select exists (
  select 1 from approvals
  where package_version_id = $1 and reviewer_id = $2
) as has_approval
`

type HasApprovalFromParams struct {
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) HasApprovalFrom(ctx context.Context, arg HasApprovalFromParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasApprovalFrom, arg.PackageVersionID, arg.ReviewerID)
	var has_approval bool
	err := row.Scan(&has_approval)
	return has_approval, err
}

const isPackageMaintainer = `-- name: IsPackageMaintainer :one
select exists (
  select 1 from package_maintainers pm
  where pm.package_id = $1
    and pm.user_id = $2
) as is_maintainer
`

type IsPackageMaintainerParams struct {
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsPackageMaintainer(ctx context.Context, arg IsPackageMaintainerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPackageMaintainer, arg.PackageID, arg.UserID)
	var is_maintainer bool
	err := row.Scan(&is_maintainer)
	return is_maintainer, err
}

const isPackageOwner = `-- name: IsPackageOwner :one
select exists (
  select 1 from package_maintainers pm
  where pm.package_id = $1
    and pm.user_id = $2
    and pm.role = 'owner'
) as is_owner
`

type IsPackageOwnerParams struct {
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsPackageOwner(ctx context.Context, arg IsPackageOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPackageOwner, arg.PackageID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
select id, token_hash, display_name, actor_user_id, actor_service_account, scopes,
       org_id, namespace_id, package_id, created_at, expires_at, last_used_at, revoked_at
from api_tokens
where actor_user_id = $1
order by created_at desc
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, actorUserID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.DisplayName,
			&i.ActorUserID,
			&i.ActorServiceAccount,
			&i.Scopes,
			&i.OrgID,
			&i.NamespaceID,
			&i.PackageID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageMaintainers = `-- name: ListPackageMaintainers :many
select pm.id, pm.package_id, pm.user_id, pm.role, pm.created_at,
       u.display_name, u.email
from package_maintainers pm
join users u on u.id = pm.user_id
where pm.package_id = $1
order by pm.role, u.display_name
`

type ListPackageMaintainersRow struct {
	ID          pgtype.UUID        `json:"id"`
	PackageID   pgtype.UUID        `json:"package_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
}

func (q *Queries) ListPackageMaintainers(ctx context.Context, packageID pgtype.UUID) ([]ListPackageMaintainersRow, error) {
	rows, err := q.db.Query(ctx, listPackageMaintainers, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageMaintainersRow{}
	for rows.Next() {
		var i ListPackageMaintainersRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewComments = `-- name: ListReviewComments :many
select rc.id, rc.review_id, rc.author_id, rc.body, rc.created_at
from review_comments rc
where rc.review_id = $1
order by rc.created_at
`

func (q *Queries) ListReviewComments(ctx context.Context, reviewID pgtype.UUID) ([]ReviewComment, error) {
	rows, err := q.db.Query(ctx, listReviewComments, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewComment{}
	for rows.Next() {
		var i ReviewComment
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewQueue = `-- name: ListReviewQueue :many
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       p.display_name as display_name,
       coalesce(p.description, '') as description,
       p.visibility as visibility,
       pv.version as version,
       pv.lifecycle as lifecycle,
       coalesce(pv.digest, '') as digest,
       r.id as review_id,
       r.package_version_id as package_version_id,
       r.reviewer_id as reviewer_id,
       r.status as review_status,
       r.created_at as created_at,
       r.updated_at as updated_at,
       coalesce(approval_counts.current_count, 0)::bigint as current_approvals
from reviews r
join package_versions pv on pv.id = r.package_version_id
join packages p on p.id = pv.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
left join lateral (
  select count(*)::bigint as current_count
  from approvals a
  where a.package_version_id = pv.id
) approval_counts on true
where pv.lifecycle = 'review'
  and p.lifecycle = 'active'
order by r.updated_at desc, r.created_at desc
limit $1::int
`

type ListReviewQueueRow struct {
	Org              string             `json:"org"`
	Namespace        string             `json:"namespace"`
	PackageName      string             `json:"package_name"`
	DisplayName      string             `json:"display_name"`
	Description      string             `json:"description"`
	Visibility       string             `json:"visibility"`
	Version          string             `json:"version"`
	Lifecycle        string             `json:"lifecycle"`
	Digest           string             `json:"digest"`
	ReviewID         pgtype.UUID        `json:"review_id"`
	PackageVersionID pgtype.UUID        `json:"package_version_id"`
	ReviewerID       pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus     string             `json:"review_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CurrentApprovals int64              `json:"current_approvals"`
}

func (q *Queries) ListReviewQueue(ctx context.Context, pageLimit int32) ([]ListReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewQueue, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewQueueRow{}
	for rows.Next() {
		var i ListReviewQueueRow
		if err := rows.Scan(
			&i.Org,
			&i.Namespace,
			&i.PackageName,
			&i.DisplayName,
			&i.Description,
			&i.Visibility,
			&i.Version,
			&i.Lifecycle,
			&i.Digest,
			&i.ReviewID,
			&i.PackageVersionID,
			&i.ReviewerID,
			&i.ReviewStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentApprovals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForVersion = `-- name: ListReviewsForVersion :many
select r.id, r.package_version_id, r.reviewer_id, r.status, r.comment, r.created_at, r.updated_at
from reviews r
where r.package_version_id = $1
order by r.created_at desc
`

func (q *Queries) ListReviewsForVersion(ctx context.Context, packageVersionID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsForVersion, packageVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.PackageVersionID,
			&i.ReviewerID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeApproval = `-- name: RemoveApproval :exec
delete from approvals
where package_version_id = $1 and reviewer_id = $2
`

type RemoveApprovalParams struct {
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) RemoveApproval(ctx context.Context, arg RemoveApprovalParams) error {
	_, err := q.db.Exec(ctx, removeApproval, arg.PackageVersionID, arg.ReviewerID)
	return err
}

const removePackageMaintainerByUser = `-- name: RemovePackageMaintainerByUser :exec
delete from package_maintainers
where package_id = $1 and user_id = $2
`

type RemovePackageMaintainerByUserParams struct {
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemovePackageMaintainerByUser(ctx context.Context, arg RemovePackageMaintainerByUserParams) error {
	_, err := q.db.Exec(ctx, removePackageMaintainerByUser, arg.PackageID, arg.UserID)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
update api_tokens
set revoked_at = now()
where id = $1 and revoked_at is null
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const updateMaintainerRole = `-- name: UpdateMaintainerRole :exec
update package_maintainers
set role = $1
where package_id = $2 and user_id = $3
`

type UpdateMaintainerRoleParams struct {
	Role      string      `json:"role"`
	PackageID pgtype.UUID `json:"package_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMaintainerRole(ctx context.Context, arg UpdateMaintainerRoleParams) error {
	_, err := q.db.Exec(ctx, updateMaintainerRole, arg.Role, arg.PackageID, arg.UserID)
	return err
}

const updateReviewStatus = `-- name: UpdateReviewStatus :one
update reviews
set status = $1, comment = coalesce($2, comment), updated_at = now()
where id = $3
returning id, package_version_id, reviewer_id, status, comment, created_at, updated_at
`

type UpdateReviewStatusParams struct {
	Status  string      `json:"status"`
	Comment pgtype.Text `json:"comment"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewStatus, arg.Status, arg.Comment, arg.ID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PackageVersionID,
		&i.ReviewerID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
update api_tokens
set last_used_at = now()
where id = $1 and revoked_at is null
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}

const upsertApproval = `-- name: UpsertApproval :exec
insert into approvals (id, package_version_id, reviewer_id, created_at)
values ($1, $2, $3, now())
on conflict (package_version_id, reviewer_id) do nothing
`

type UpsertApprovalParams struct {
	ID               pgtype.UUID `json:"id"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) UpsertApproval(ctx context.Context, arg UpsertApprovalParams) error {
	_, err := q.db.Exec(ctx, upsertApproval, arg.ID, arg.PackageVersionID, arg.ReviewerID)
	return err
}
