// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ArtifactBlob struct {
	Digest    string             `json:"digest"`
	Content   []byte             `json:"content"`
	SizeBytes int64              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArtifactFile struct {
	ID               pgtype.UUID        `json:"id"`
	PackageVersionID pgtype.UUID        `json:"package_version_id"`
	Path             string             `json:"path"`
	Type             string             `json:"type"`
	ContentType      string             `json:"content_type"`
	BlobDigest       string             `json:"blob_digest"`
	SizeBytes        int64              `json:"size_bytes"`
	TargetPath       pgtype.Text        `json:"target_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ArtifactLocation struct {
	Digest        string             `json:"digest"`
	StorageDriver string             `json:"storage_driver"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	NamespaceID         pgtype.UUID        `json:"namespace_id"`
	PackageID           pgtype.UUID        `json:"package_id"`
	PackageVersionID    pgtype.UUID        `json:"package_version_id"`
	ActorUserID         pgtype.UUID        `json:"actor_user_id"`
	ActorServiceAccount pgtype.Text        `json:"actor_service_account"`
	Action              string             `json:"action"`
	MetadataJson        []byte             `json:"metadata_json"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID               pgtype.UUID        `json:"id"`
	PackageID        pgtype.UUID        `json:"package_id"`
	Name             string             `json:"name"`
	PackageVersionID pgtype.UUID        `json:"package_version_id"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Namespace struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	OwnerTeamID pgtype.UUID        `json:"owner_team_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Package struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	Lifecycle   string             `json:"lifecycle"`
	OwnerTeamID pgtype.UUID        `json:"owner_team_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PackageVersion struct {
	ID           pgtype.UUID        `json:"id"`
	PackageID    pgtype.UUID        `json:"package_id"`
	Version      string             `json:"version"`
	SemverMajor  pgtype.Int4        `json:"semver_major"`
	SemverMinor  pgtype.Int4        `json:"semver_minor"`
	SemverPatch  pgtype.Int4        `json:"semver_patch"`
	Lifecycle    string             `json:"lifecycle"`
	Visibility   string             `json:"visibility"`
	Channel      pgtype.Text        `json:"channel"`
	ManifestJson []byte             `json:"manifest_json"`
	Changelog    pgtype.Text        `json:"changelog"`
	Digest       pgtype.Text        `json:"digest"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	PublishedBy  pgtype.UUID        `json:"published_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}
