// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_path.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getManifest = `-- name: GetManifest :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as version,
       coalesce(v.digest, '') as digest,
       v.manifest_json as manifest_json
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
  and v.lifecycle in ('published', 'deprecated', 'yanked')
`

type GetManifestParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type GetManifestRow struct {
	Org          string `json:"org"`
	Namespace    string `json:"namespace"`
	PackageName  string `json:"package_name"`
	Version      string `json:"version"`
	Digest       string `json:"digest"`
	ManifestJson []byte `json:"manifest_json"`
}

func (q *Queries) GetManifest(ctx context.Context, arg GetManifestParams) (GetManifestRow, error) {
	row := q.db.QueryRow(ctx, getManifest,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i GetManifestRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.Version,
		&i.Digest,
		&i.ManifestJson,
	)
	return i, err
}

const getPackageAdoption = `-- name: GetPackageAdoption :one
select count(distinct pai.project_id)::bigint as project_count,
       count(distinct pai.package_version_id)::bigint as version_count
from project_artifact_installs pai
join packages p on p.id = pai.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
`

type GetPackageAdoptionParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type GetPackageAdoptionRow struct {
	ProjectCount int64 `json:"project_count"`
	VersionCount int64 `json:"version_count"`
}

func (q *Queries) GetPackageAdoption(ctx context.Context, arg GetPackageAdoptionParams) (GetPackageAdoptionRow, error) {
	row := q.db.QueryRow(ctx, getPackageAdoption, arg.Org, arg.Namespace, arg.PackageName)
	var i GetPackageAdoptionRow
	err := row.Scan(&i.ProjectCount, &i.VersionCount)
	return i, err
}

const getPackageSummary = `-- name: GetPackageSummary :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       p.display_name as display_name,
       coalesce(p.description, '') as description,
       p.visibility as visibility,
       p.lifecycle as lifecycle,
       coalesce(latest.version, '') as latest_version
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
left join lateral (
  select v.version
  from package_versions v
  where v.package_id = p.id
    and v.lifecycle in ('published', 'deprecated', 'yanked')
  order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
  limit 1
) latest on true
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and p.lifecycle = 'active'
`

type GetPackageSummaryParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type GetPackageSummaryRow struct {
	Org           string `json:"org"`
	Namespace     string `json:"namespace"`
	PackageName   string `json:"package_name"`
	DisplayName   string `json:"display_name"`
	Description   string `json:"description"`
	Visibility    string `json:"visibility"`
	Lifecycle     string `json:"lifecycle"`
	LatestVersion string `json:"latest_version"`
}

func (q *Queries) GetPackageSummary(ctx context.Context, arg GetPackageSummaryParams) (GetPackageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPackageSummary, arg.Org, arg.Namespace, arg.PackageName)
	var i GetPackageSummaryRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.DisplayName,
		&i.Description,
		&i.Visibility,
		&i.Lifecycle,
		&i.LatestVersion,
	)
	return i, err
}

const getRawArtifact = `-- name: GetRawArtifact :one
select af.path as path,
       af.content_type as content_type,
       af.blob_digest as blob_digest,
       af.size_bytes as size_bytes,
       ab.content as content,
       case
         when o.visibility = 'public' and n.visibility = 'public' and p.visibility = 'public' and v.visibility = 'public'
         then 'public, max-age=31536000, immutable'
         else 'private, max-age=31536000, immutable'
       end as cache_control
from artifact_files af
join package_versions v on v.id = af.package_version_id
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
join artifact_blobs ab on ab.digest = af.blob_digest
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
  and af.path = $5
  and v.lifecycle in ('published', 'deprecated', 'yanked')
`

type GetRawArtifactParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
	Path        string `json:"path"`
}

type GetRawArtifactRow struct {
	Path         string `json:"path"`
	ContentType  string `json:"content_type"`
	BlobDigest   string `json:"blob_digest"`
	SizeBytes    int64  `json:"size_bytes"`
	Content      []byte `json:"content"`
	CacheControl string `json:"cache_control"`
}

func (q *Queries) GetRawArtifact(ctx context.Context, arg GetRawArtifactParams) (GetRawArtifactRow, error) {
	row := q.db.QueryRow(ctx, getRawArtifact,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
		arg.Path,
	)
	var i GetRawArtifactRow
	err := row.Scan(
		&i.Path,
		&i.ContentType,
		&i.BlobDigest,
		&i.SizeBytes,
		&i.Content,
		&i.CacheControl,
	)
	return i, err
}

const listArchiveArtifacts = `-- name: ListArchiveArtifacts :many
select af.path as path,
       ab.content as content
from artifact_files af
join package_versions v on v.id = af.package_version_id
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
join artifact_blobs ab on ab.digest = af.blob_digest
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
  and v.lifecycle in ('published', 'deprecated', 'yanked')
order by af.path
`

type ListArchiveArtifactsParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type ListArchiveArtifactsRow struct {
	Path    string `json:"path"`
	Content []byte `json:"content"`
}

func (q *Queries) ListArchiveArtifacts(ctx context.Context, arg ListArchiveArtifactsParams) ([]ListArchiveArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArchiveArtifacts,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchiveArtifactsRow{}
	for rows.Next() {
		var i ListArchiveArtifactsRow
		if err := rows.Scan(&i.Path, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageVersions = `-- name: ListPackageVersions :many
select v.version as version,
       coalesce(v.digest, '') as digest,
       v.lifecycle as lifecycle,
       coalesce(to_char(v.published_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as published_at
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.lifecycle in ('published', 'deprecated', 'yanked')
order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
`

type ListPackageVersionsParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type ListPackageVersionsRow struct {
	Version     string `json:"version"`
	Digest      string `json:"digest"`
	Lifecycle   string `json:"lifecycle"`
	PublishedAt string `json:"published_at"`
}

func (q *Queries) ListPackageVersions(ctx context.Context, arg ListPackageVersionsParams) ([]ListPackageVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPackageVersions, arg.Org, arg.Namespace, arg.PackageName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageVersionsRow{}
	for rows.Next() {
		var i ListPackageVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Digest,
			&i.Lifecycle,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageVersionsByAdoption = `-- name: ListPackageVersionsByAdoption :many
select pv.version,
       count(pai.id)::bigint as install_count
from project_artifact_installs pai
join package_versions pv on pv.id = pai.package_version_id
join packages p on p.id = pv.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
group by pv.version
order by install_count desc, pv.semver_major desc, pv.semver_minor desc, pv.semver_patch desc
`

type ListPackageVersionsByAdoptionParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type ListPackageVersionsByAdoptionRow struct {
	Version      string `json:"version"`
	InstallCount int64  `json:"install_count"`
}

func (q *Queries) ListPackageVersionsByAdoption(ctx context.Context, arg ListPackageVersionsByAdoptionParams) ([]ListPackageVersionsByAdoptionRow, error) {
	rows, err := q.db.Query(ctx, listPackageVersionsByAdoption, arg.Org, arg.Namespace, arg.PackageName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageVersionsByAdoptionRow{}
	for rows.Next() {
		var i ListPackageVersionsByAdoptionRow
		if err := rows.Scan(&i.Version, &i.InstallCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       p.display_name as display_name,
       coalesce(p.description, '') as description,
       p.visibility as visibility,
       p.lifecycle as lifecycle,
       coalesce(latest.version, '') as latest_version
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
left join lateral (
  select v.version
  from package_versions v
  where v.package_id = p.id
    and v.lifecycle in ('published', 'deprecated', 'yanked')
  order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
  limit 1
) latest on true
where p.lifecycle = 'active'
  and exists (select 1 from package_versions v where v.package_id = p.id and v.lifecycle = 'published')
  and (($1::text = '') or ((o.slug || '/' || n.slug || '/' || p.name) > $1::text))
order by o.slug, n.slug, p.name
limit $2::int
`

type ListPackagesParams struct {
	Cursor    string `json:"cursor"`
	PageLimit int32  `json:"page_limit"`
}

type ListPackagesRow struct {
	Org           string `json:"org"`
	Namespace     string `json:"namespace"`
	PackageName   string `json:"package_name"`
	DisplayName   string `json:"display_name"`
	Description   string `json:"description"`
	Visibility    string `json:"visibility"`
	Lifecycle     string `json:"lifecycle"`
	LatestVersion string `json:"latest_version"`
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesRow{}
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.Org,
			&i.Namespace,
			&i.PackageName,
			&i.DisplayName,
			&i.Description,
			&i.Visibility,
			&i.Lifecycle,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDigest = `-- name: ResolveDigest :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as resolved_version,
       coalesce(v.digest, '') as digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.digest = $4::text
  and v.lifecycle in ('published', 'deprecated', 'yanked')
`

type ResolveDigestParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Digest      string `json:"digest"`
}

type ResolveDigestRow struct {
	Org             string `json:"org"`
	Namespace       string `json:"namespace"`
	PackageName     string `json:"package_name"`
	ResolvedVersion string `json:"resolved_version"`
	Digest          string `json:"digest"`
}

func (q *Queries) ResolveDigest(ctx context.Context, arg ResolveDigestParams) (ResolveDigestRow, error) {
	row := q.db.QueryRow(ctx, resolveDigest,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Digest,
	)
	var i ResolveDigestRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.ResolvedVersion,
		&i.Digest,
	)
	return i, err
}

const resolveExact = `-- name: ResolveExact :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as resolved_version,
       coalesce(v.digest, '') as digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
  and v.lifecycle in ('published', 'deprecated', 'yanked')
`

type ResolveExactParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type ResolveExactRow struct {
	Org             string `json:"org"`
	Namespace       string `json:"namespace"`
	PackageName     string `json:"package_name"`
	ResolvedVersion string `json:"resolved_version"`
	Digest          string `json:"digest"`
}

func (q *Queries) ResolveExact(ctx context.Context, arg ResolveExactParams) (ResolveExactRow, error) {
	row := q.db.QueryRow(ctx, resolveExact,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i ResolveExactRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.ResolvedVersion,
		&i.Digest,
	)
	return i, err
}

const resolveLatest = `-- name: ResolveLatest :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as resolved_version,
       coalesce(v.digest, '') as digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.lifecycle in ('published', 'deprecated', 'yanked')
order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
limit 1
`

type ResolveLatestParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type ResolveLatestRow struct {
	Org             string `json:"org"`
	Namespace       string `json:"namespace"`
	PackageName     string `json:"package_name"`
	ResolvedVersion string `json:"resolved_version"`
	Digest          string `json:"digest"`
}

func (q *Queries) ResolveLatest(ctx context.Context, arg ResolveLatestParams) (ResolveLatestRow, error) {
	row := q.db.QueryRow(ctx, resolveLatest, arg.Org, arg.Namespace, arg.PackageName)
	var i ResolveLatestRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.ResolvedVersion,
		&i.Digest,
	)
	return i, err
}

const resolveMajor = `-- name: ResolveMajor :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as resolved_version,
       coalesce(v.digest, '') as digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.semver_major = $4
  and v.lifecycle in ('published', 'deprecated', 'yanked')
order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
limit 1
`

type ResolveMajorParams struct {
	Org         string      `json:"org"`
	Namespace   string      `json:"namespace"`
	PackageName string      `json:"package_name"`
	Major       pgtype.Int4 `json:"major"`
}

type ResolveMajorRow struct {
	Org             string `json:"org"`
	Namespace       string `json:"namespace"`
	PackageName     string `json:"package_name"`
	ResolvedVersion string `json:"resolved_version"`
	Digest          string `json:"digest"`
}

func (q *Queries) ResolveMajor(ctx context.Context, arg ResolveMajorParams) (ResolveMajorRow, error) {
	row := q.db.QueryRow(ctx, resolveMajor,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Major,
	)
	var i ResolveMajorRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.ResolvedVersion,
		&i.Digest,
	)
	return i, err
}

const resolveMinor = `-- name: ResolveMinor :one
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       v.version as resolved_version,
       coalesce(v.digest, '') as digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.semver_major = $4
  and v.semver_minor = $5
  and v.lifecycle in ('published', 'deprecated', 'yanked')
order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
limit 1
`

type ResolveMinorParams struct {
	Org         string      `json:"org"`
	Namespace   string      `json:"namespace"`
	PackageName string      `json:"package_name"`
	Major       pgtype.Int4 `json:"major"`
	Minor       pgtype.Int4 `json:"minor"`
}

type ResolveMinorRow struct {
	Org             string `json:"org"`
	Namespace       string `json:"namespace"`
	PackageName     string `json:"package_name"`
	ResolvedVersion string `json:"resolved_version"`
	Digest          string `json:"digest"`
}

func (q *Queries) ResolveMinor(ctx context.Context, arg ResolveMinorParams) (ResolveMinorRow, error) {
	row := q.db.QueryRow(ctx, resolveMinor,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Major,
		arg.Minor,
	)
	var i ResolveMinorRow
	err := row.Scan(
		&i.Org,
		&i.Namespace,
		&i.PackageName,
		&i.ResolvedVersion,
		&i.Digest,
	)
	return i, err
}

const searchPackages = `-- name: SearchPackages :many
select o.slug as org,
       n.slug as namespace,
       p.name as package_name,
       p.display_name as display_name,
       coalesce(p.description, '') as description,
       p.visibility as visibility,
       p.lifecycle as lifecycle,
       coalesce(latest.version, '') as latest_version,
       ts_rank(sd.search_text, plainto_tsquery('english', $1::text)) as rank
from package_search_documents sd
join packages p on p.id = sd.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
left join lateral (
  select v.version
  from package_versions v
  where v.package_id = p.id
    and v.lifecycle in ('published', 'deprecated', 'yanked')
  order by v.semver_major desc, v.semver_minor desc, v.semver_patch desc
  limit 1
) latest on true
where sd.search_text @@ plainto_tsquery('english', $1::text)
  and sd.lifecycle = 'active'
  and sd.visibility = 'public'
  and ($2::text = '' or o.slug = $2::text)
  and ($3::text = '' or n.slug = $3::text)
  and ($4::text = '' or $4::text = any(sd.artifact_types))
  and ($5::text = '' or $5::text = any(sd.tool_names))
  and (($6::text = '') or ((o.slug || '/' || n.slug || '/' || p.name) > $6::text))
order by rank desc, o.slug, n.slug, p.name
limit $7::int
`

type SearchPackagesParams struct {
	Query        string `json:"query"`
	Org          string `json:"org"`
	Namespace    string `json:"namespace"`
	ArtifactType string `json:"artifact_type"`
	Tool         string `json:"tool"`
	Cursor       string `json:"cursor"`
	PageLimit    int32  `json:"page_limit"`
}

type SearchPackagesRow struct {
	Org           string  `json:"org"`
	Namespace     string  `json:"namespace"`
	PackageName   string  `json:"package_name"`
	DisplayName   string  `json:"display_name"`
	Description   string  `json:"description"`
	Visibility    string  `json:"visibility"`
	Lifecycle     string  `json:"lifecycle"`
	LatestVersion string  `json:"latest_version"`
	Rank          float32 `json:"rank"`
}

func (q *Queries) SearchPackages(ctx context.Context, arg SearchPackagesParams) ([]SearchPackagesRow, error) {
	rows, err := q.db.Query(ctx, searchPackages,
		arg.Query,
		arg.Org,
		arg.Namespace,
		arg.ArtifactType,
		arg.Tool,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPackagesRow{}
	for rows.Next() {
		var i SearchPackagesRow
		if err := rows.Scan(
			&i.Org,
			&i.Namespace,
			&i.PackageName,
			&i.DisplayName,
			&i.Description,
			&i.Visibility,
			&i.Lifecycle,
			&i.LatestVersion,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
