// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: write_path.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftVersion = `-- name: CreateDraftVersion :one
insert into package_versions (
  id,
  package_id,
  version,
  semver_major,
  semver_minor,
  semver_patch,
  lifecycle,
  visibility,
  manifest_json,
  created_at,
  updated_at
)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  'draft',
  $7,
  '{}'::jsonb,
  now(),
  now()
)
returning id, version, lifecycle, visibility, digest, created_at, updated_at, published_at
`

type CreateDraftVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	PackageID   pgtype.UUID `json:"package_id"`
	Version     string      `json:"version"`
	SemverMajor pgtype.Int4 `json:"semver_major"`
	SemverMinor pgtype.Int4 `json:"semver_minor"`
	SemverPatch pgtype.Int4 `json:"semver_patch"`
	Visibility  string      `json:"visibility"`
}

type CreateDraftVersionRow struct {
	ID          pgtype.UUID        `json:"id"`
	Version     string             `json:"version"`
	Lifecycle   string             `json:"lifecycle"`
	Visibility  string             `json:"visibility"`
	Digest      pgtype.Text        `json:"digest"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateDraftVersion(ctx context.Context, arg CreateDraftVersionParams) (CreateDraftVersionRow, error) {
	row := q.db.QueryRow(ctx, createDraftVersion,
		arg.ID,
		arg.PackageID,
		arg.Version,
		arg.SemverMajor,
		arg.SemverMinor,
		arg.SemverPatch,
		arg.Visibility,
	)
	var i CreateDraftVersionRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPackageID = `-- name: GetPackageID :one
select p.id
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
`

type GetPackageIDParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

func (q *Queries) GetPackageID(ctx context.Context, arg GetPackageIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPackageID, arg.Org, arg.Namespace, arg.PackageName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getVersionForUpdate = `-- name: GetVersionForUpdate :one
select v.id,
       v.package_id,
       v.version,
       v.lifecycle,
       v.visibility,
       v.manifest_json,
       v.digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
for update
`

type GetVersionForUpdateParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type GetVersionForUpdateRow struct {
	ID           pgtype.UUID `json:"id"`
	PackageID    pgtype.UUID `json:"package_id"`
	Version      string      `json:"version"`
	Lifecycle    string      `json:"lifecycle"`
	Visibility   string      `json:"visibility"`
	ManifestJson []byte      `json:"manifest_json"`
	Digest       pgtype.Text `json:"digest"`
}

func (q *Queries) GetVersionForUpdate(ctx context.Context, arg GetVersionForUpdateParams) (GetVersionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVersionForUpdate,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i GetVersionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.ManifestJson,
		&i.Digest,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
insert into audit_events (id, org_id, namespace_id, package_id, package_version_id, actor_service_account, action, metadata_json, created_at)
select $1, p.org_id, p.namespace_id, p.id, $2, $3, $4, $5, now()
from packages p
where p.id = $6
`

type InsertAuditEventParams struct {
	ID                  pgtype.UUID `json:"id"`
	PackageVersionID    pgtype.UUID `json:"package_version_id"`
	ActorServiceAccount pgtype.Text `json:"actor_service_account"`
	Action              string      `json:"action"`
	MetadataJson        []byte      `json:"metadata_json"`
	PackageID           pgtype.UUID `json:"package_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.PackageVersionID,
		arg.ActorServiceAccount,
		arg.Action,
		arg.MetadataJson,
		arg.PackageID,
	)
	return err
}

const listArtifactMetadataForVersion = `-- name: ListArtifactMetadataForVersion :many
select path, type, blob_digest, size_bytes, coalesce(target_path, '') as target_path
from artifact_files
where package_version_id = $1
order by path
`

type ListArtifactMetadataForVersionRow struct {
	Path       string `json:"path"`
	Type       string `json:"type"`
	BlobDigest string `json:"blob_digest"`
	SizeBytes  int64  `json:"size_bytes"`
	TargetPath string `json:"target_path"`
}

func (q *Queries) ListArtifactMetadataForVersion(ctx context.Context, packageVersionID pgtype.UUID) ([]ListArtifactMetadataForVersionRow, error) {
	rows, err := q.db.Query(ctx, listArtifactMetadataForVersion, packageVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactMetadataForVersionRow{}
	for rows.Next() {
		var i ListArtifactMetadataForVersionRow
		if err := rows.Scan(
			&i.Path,
			&i.Type,
			&i.BlobDigest,
			&i.SizeBytes,
			&i.TargetPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishVersion = `-- name: PublishVersion :one
update package_versions
set lifecycle = 'published',
    digest = $1,
    updated_at = now(),
    published_at = now()
where id = $2
returning version, lifecycle, digest, published_at
`

type PublishVersionParams struct {
	Digest pgtype.Text `json:"digest"`
	ID     pgtype.UUID `json:"id"`
}

type PublishVersionRow struct {
	Version     string             `json:"version"`
	Lifecycle   string             `json:"lifecycle"`
	Digest      pgtype.Text        `json:"digest"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) PublishVersion(ctx context.Context, arg PublishVersionParams) (PublishVersionRow, error) {
	row := q.db.QueryRow(ctx, publishVersion, arg.Digest, arg.ID)
	var i PublishVersionRow
	err := row.Scan(
		&i.Version,
		&i.Lifecycle,
		&i.Digest,
		&i.PublishedAt,
	)
	return i, err
}

const updateVersionManifest = `-- name: UpdateVersionManifest :exec
update package_versions
set manifest_json = $1,
    visibility = $2,
    channel = $3,
    updated_at = now()
where id = $4
`

type UpdateVersionManifestParams struct {
	ManifestJson []byte      `json:"manifest_json"`
	Visibility   string      `json:"visibility"`
	Channel      pgtype.Text `json:"channel"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVersionManifest(ctx context.Context, arg UpdateVersionManifestParams) error {
	_, err := q.db.Exec(ctx, updateVersionManifest,
		arg.ManifestJson,
		arg.Visibility,
		arg.Channel,
		arg.ID,
	)
	return err
}

const upsertArtifactBlob = `-- name: UpsertArtifactBlob :exec
insert into artifact_blobs (digest, content, size_bytes, created_at)
values ($1, $2, $3, now())
on conflict (digest) do nothing
`

type UpsertArtifactBlobParams struct {
	Digest    string `json:"digest"`
	Content   []byte `json:"content"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertArtifactBlob(ctx context.Context, arg UpsertArtifactBlobParams) error {
	_, err := q.db.Exec(ctx, upsertArtifactBlob, arg.Digest, arg.Content, arg.SizeBytes)
	return err
}

const upsertArtifactFile = `-- name: UpsertArtifactFile :one
insert into artifact_files (id, package_version_id, path, type, content_type, blob_digest, size_bytes, target_path, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, now())
on conflict (package_version_id, path) do update
set type = excluded.type,
    content_type = excluded.content_type,
    blob_digest = excluded.blob_digest,
    size_bytes = excluded.size_bytes,
    target_path = excluded.target_path
returning id, path, type, content_type, blob_digest, size_bytes, target_path, created_at
`

type UpsertArtifactFileParams struct {
	ID               pgtype.UUID `json:"id"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	Path             string      `json:"path"`
	Type             string      `json:"type"`
	ContentType      string      `json:"content_type"`
	BlobDigest       string      `json:"blob_digest"`
	SizeBytes        int64       `json:"size_bytes"`
	TargetPath       pgtype.Text `json:"target_path"`
}

type UpsertArtifactFileRow struct {
	ID          pgtype.UUID        `json:"id"`
	Path        string             `json:"path"`
	Type        string             `json:"type"`
	ContentType string             `json:"content_type"`
	BlobDigest  string             `json:"blob_digest"`
	SizeBytes   int64              `json:"size_bytes"`
	TargetPath  pgtype.Text        `json:"target_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertArtifactFile(ctx context.Context, arg UpsertArtifactFileParams) (UpsertArtifactFileRow, error) {
	row := q.db.QueryRow(ctx, upsertArtifactFile,
		arg.ID,
		arg.PackageVersionID,
		arg.Path,
		arg.Type,
		arg.ContentType,
		arg.BlobDigest,
		arg.SizeBytes,
		arg.TargetPath,
	)
	var i UpsertArtifactFileRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Type,
		&i.ContentType,
		&i.BlobDigest,
		&i.SizeBytes,
		&i.TargetPath,
		&i.CreatedAt,
	)
	return i, err
}

const upsertArtifactLocation = `-- name: UpsertArtifactLocation :exec
insert into artifact_locations (digest, storage_driver, storage_uri, created_at)
values ($1, 'postgres', null, now())
on conflict (digest) do nothing
`

func (q *Queries) UpsertArtifactLocation(ctx context.Context, digest string) error {
	_, err := q.db.Exec(ctx, upsertArtifactLocation, digest)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
insert into channels (id, package_id, name, package_version_id, updated_at)
values ($1, $2, $3, $4, now())
on conflict (package_id, name) do update
set package_version_id = excluded.package_version_id,
    updated_at = excluded.updated_at
`

type UpsertChannelParams struct {
	ID               pgtype.UUID `json:"id"`
	PackageID        pgtype.UUID `json:"package_id"`
	Name             string      `json:"name"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.Exec(ctx, upsertChannel,
		arg.ID,
		arg.PackageID,
		arg.Name,
		arg.PackageVersionID,
	)
	return err
}
