// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: write_path.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftVersion = `-- name: CreateDraftVersion :one
insert into package_versions (
  id,
  package_id,
  version,
  semver_major,
  semver_minor,
  semver_patch,
  lifecycle,
  visibility,
  manifest_json,
  created_at,
  updated_at
)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  'draft',
  $7,
  '{}'::jsonb,
  now(),
  now()
)
returning id, version, lifecycle, visibility, digest, created_at, updated_at, published_at
`

type CreateDraftVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	PackageID   pgtype.UUID `json:"package_id"`
	Version     string      `json:"version"`
	SemverMajor pgtype.Int4 `json:"semver_major"`
	SemverMinor pgtype.Int4 `json:"semver_minor"`
	SemverPatch pgtype.Int4 `json:"semver_patch"`
	Visibility  string      `json:"visibility"`
}

type CreateDraftVersionRow struct {
	ID          pgtype.UUID        `json:"id"`
	Version     string             `json:"version"`
	Lifecycle   string             `json:"lifecycle"`
	Visibility  string             `json:"visibility"`
	Digest      pgtype.Text        `json:"digest"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateDraftVersion(ctx context.Context, arg CreateDraftVersionParams) (CreateDraftVersionRow, error) {
	row := q.db.QueryRow(ctx, createDraftVersion,
		arg.ID,
		arg.PackageID,
		arg.Version,
		arg.SemverMajor,
		arg.SemverMinor,
		arg.SemverPatch,
		arg.Visibility,
	)
	var i CreateDraftVersionRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createNamespace = `-- name: CreateNamespace :one
insert into namespaces (id, org_id, slug, display_name, visibility, created_at, updated_at)
values (
  $1,
  (select o.id from organizations o where o.slug = $2),
  $3,
  $4,
  $5,
  now(),
  now()
)
returning id, org_id, slug, display_name, visibility, created_at, updated_at
`

type CreateNamespaceParams struct {
	ID            pgtype.UUID `json:"id"`
	OrgSlug       string      `json:"org_slug"`
	NamespaceSlug string      `json:"namespace_slug"`
	DisplayName   string      `json:"display_name"`
	Visibility    string      `json:"visibility"`
}

type CreateNamespaceRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (CreateNamespaceRow, error) {
	row := q.db.QueryRow(ctx, createNamespace,
		arg.ID,
		arg.OrgSlug,
		arg.NamespaceSlug,
		arg.DisplayName,
		arg.Visibility,
	)
	var i CreateNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
insert into organizations (id, slug, display_name, visibility, created_at, updated_at)
values ($1, $2, $3, $4, now(), now())
returning id, slug, display_name, visibility, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Visibility  string      `json:"visibility"`
}

type CreateOrganizationRow struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Visibility,
	)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPackage = `-- name: CreatePackage :one
insert into packages (id, org_id, namespace_id, name, display_name, description, visibility, lifecycle, created_at, updated_at)
values (
  $1,
  (select o.id from organizations o where o.slug = $2),
  (select n.id from namespaces n join organizations o on o.id = n.org_id where o.slug = $2 and n.slug = $3),
  $4,
  $5,
  $6,
  $7,
  'active',
  now(),
  now()
)
returning id, namespace_id, name, display_name, description, visibility, lifecycle, created_at, updated_at
`

type CreatePackageParams struct {
	ID            pgtype.UUID `json:"id"`
	OrgSlug       string      `json:"org_slug"`
	NamespaceSlug string      `json:"namespace_slug"`
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	Visibility    string      `json:"visibility"`
}

type CreatePackageRow struct {
	ID          pgtype.UUID        `json:"id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	Lifecycle   string             `json:"lifecycle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (CreatePackageRow, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.ID,
		arg.OrgSlug,
		arg.NamespaceSlug,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Visibility,
	)
	var i CreatePackageRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Visibility,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectRegistration = `-- name: CreateProjectRegistration :one
insert into project_registrations (id, org_id, name, repo_url, team_id, metadata_json, last_seen_at, created_at)
values (
  $1,
  (select o.id from organizations o where o.slug = $2),
  $3,
  $4,
  $5,
  $6,
  now(),
  now()
)
on conflict (org_id, repo_url) do update
set name = excluded.name,
    team_id = excluded.team_id,
    metadata_json = excluded.metadata_json,
    last_seen_at = now()
returning id, org_id, name, repo_url, created_at
`

type CreateProjectRegistrationParams struct {
	ID           pgtype.UUID `json:"id"`
	OrgSlug      string      `json:"org_slug"`
	Name         string      `json:"name"`
	RepoUrl      string      `json:"repo_url"`
	TeamID       pgtype.UUID `json:"team_id"`
	MetadataJson []byte      `json:"metadata_json"`
}

type CreateProjectRegistrationRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	RepoUrl   string             `json:"repo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProjectRegistration(ctx context.Context, arg CreateProjectRegistrationParams) (CreateProjectRegistrationRow, error) {
	row := q.db.QueryRow(ctx, createProjectRegistration,
		arg.ID,
		arg.OrgSlug,
		arg.Name,
		arg.RepoUrl,
		arg.TeamID,
		arg.MetadataJson,
	)
	var i CreateProjectRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deprecateVersion = `-- name: DeprecateVersion :one
update package_versions
set lifecycle = 'deprecated',
    updated_at = now()
where id = $1
  and lifecycle = 'published'
returning version, lifecycle, updated_at
`

type DeprecateVersionRow struct {
	Version   string             `json:"version"`
	Lifecycle string             `json:"lifecycle"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeprecateVersion(ctx context.Context, id pgtype.UUID) (DeprecateVersionRow, error) {
	row := q.db.QueryRow(ctx, deprecateVersion, id)
	var i DeprecateVersionRow
	err := row.Scan(&i.Version, &i.Lifecycle, &i.UpdatedAt)
	return i, err
}

const ensureNamespace = `-- name: EnsureNamespace :one
with org_row as (
  select id from organizations where organizations.slug = $5
)
insert into namespaces (id, org_id, slug, display_name, visibility, created_at, updated_at)
select
  $1,
  org_row.id,
  $2,
  $3,
  $4,
  now(),
  now()
from org_row
on conflict (org_id, slug) do update set slug = namespaces.slug
returning id, org_id, slug, display_name, visibility, created_at, updated_at
`

type EnsureNamespaceParams struct {
	ID            pgtype.UUID `json:"id"`
	NamespaceSlug string      `json:"namespace_slug"`
	DisplayName   string      `json:"display_name"`
	Visibility    string      `json:"visibility"`
	OrgSlug       string      `json:"org_slug"`
}

type EnsureNamespaceRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) EnsureNamespace(ctx context.Context, arg EnsureNamespaceParams) (EnsureNamespaceRow, error) {
	row := q.db.QueryRow(ctx, ensureNamespace,
		arg.ID,
		arg.NamespaceSlug,
		arg.DisplayName,
		arg.Visibility,
		arg.OrgSlug,
	)
	var i EnsureNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureOrganization = `-- name: EnsureOrganization :one
insert into organizations (id, slug, display_name, visibility, created_at, updated_at)
values ($1, $2, $3, $4, now(), now())
on conflict (slug) do update set slug = organizations.slug
returning id, slug, display_name, visibility, created_at, updated_at
`

type EnsureOrganizationParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Visibility  string      `json:"visibility"`
}

type EnsureOrganizationRow struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) EnsureOrganization(ctx context.Context, arg EnsureOrganizationParams) (EnsureOrganizationRow, error) {
	row := q.db.QueryRow(ctx, ensureOrganization,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Visibility,
	)
	var i EnsureOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePackage = `-- name: EnsurePackage :one
with namespace_row as (
  select o.id as org_id, n.id as namespace_id
  from namespaces n
  join organizations o on o.id = n.org_id
  where o.slug = $6
    and n.slug = $7
)
insert into packages (id, org_id, namespace_id, name, display_name, description, visibility, lifecycle, created_at, updated_at)
select
  $1,
  namespace_row.org_id,
  namespace_row.namespace_id,
  $2,
  $3,
  $4,
  $5,
  'active',
  now(),
  now()
from namespace_row
on conflict (namespace_id, name) do update set name = packages.name
returning id, namespace_id, name, display_name, description, visibility, lifecycle, created_at, updated_at
`

type EnsurePackageParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	Visibility    string      `json:"visibility"`
	OrgSlug       string      `json:"org_slug"`
	NamespaceSlug string      `json:"namespace_slug"`
}

type EnsurePackageRow struct {
	ID          pgtype.UUID        `json:"id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	Lifecycle   string             `json:"lifecycle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) EnsurePackage(ctx context.Context, arg EnsurePackageParams) (EnsurePackageRow, error) {
	row := q.db.QueryRow(ctx, ensurePackage,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Visibility,
		arg.OrgSlug,
		arg.NamespaceSlug,
	)
	var i EnsurePackageRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Visibility,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageID = `-- name: GetPackageID :one
select p.id
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
`

type GetPackageIDParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

func (q *Queries) GetPackageID(ctx context.Context, arg GetPackageIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPackageID, arg.Org, arg.Namespace, arg.PackageName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPackageIDForProjectInstall = `-- name: GetPackageIDForProjectInstall :one
select p.id
from packages p
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
`

type GetPackageIDForProjectInstallParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

func (q *Queries) GetPackageIDForProjectInstall(ctx context.Context, arg GetPackageIDForProjectInstallParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPackageIDForProjectInstall, arg.Org, arg.Namespace, arg.PackageName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPackageVersionAny = `-- name: GetPackageVersionAny :one
select v.version,
       v.lifecycle,
       v.visibility,
       coalesce(v.digest, '') as digest,
       coalesce(to_char(v.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as created_at,
       coalesce(to_char(v.updated_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as updated_at,
       coalesce(to_char(v.published_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as published_at
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
`

type GetPackageVersionAnyParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type GetPackageVersionAnyRow struct {
	Version     string `json:"version"`
	Lifecycle   string `json:"lifecycle"`
	Visibility  string `json:"visibility"`
	Digest      string `json:"digest"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	PublishedAt string `json:"published_at"`
}

func (q *Queries) GetPackageVersionAny(ctx context.Context, arg GetPackageVersionAnyParams) (GetPackageVersionAnyRow, error) {
	row := q.db.QueryRow(ctx, getPackageVersionAny,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i GetPackageVersionAnyRow
	err := row.Scan(
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPackageVersionIDForProjectInstall = `-- name: GetPackageVersionIDForProjectInstall :one
select v.id
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
`

type GetPackageVersionIDForProjectInstallParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

func (q *Queries) GetPackageVersionIDForProjectInstall(ctx context.Context, arg GetPackageVersionIDForProjectInstallParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPackageVersionIDForProjectInstall,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectByRepoURL = `-- name: GetProjectByRepoURL :one
select pr.id, pr.org_id, pr.name, pr.repo_url, pr.team_id, pr.metadata_json, pr.last_seen_at, pr.created_at
from project_registrations pr
join organizations o on o.id = pr.org_id
where o.slug = $1
  and pr.repo_url = $2
`

type GetProjectByRepoURLParams struct {
	OrgSlug string `json:"org_slug"`
	RepoUrl string `json:"repo_url"`
}

func (q *Queries) GetProjectByRepoURL(ctx context.Context, arg GetProjectByRepoURLParams) (ProjectRegistration, error) {
	row := q.db.QueryRow(ctx, getProjectByRepoURL, arg.OrgSlug, arg.RepoUrl)
	var i ProjectRegistration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RepoUrl,
		&i.TeamID,
		&i.MetadataJson,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionForUpdate = `-- name: GetVersionForUpdate :one
select v.id,
       v.package_id,
       v.version,
       v.lifecycle,
       v.visibility,
       v.manifest_json,
       v.digest
from package_versions v
join packages p on p.id = v.package_id
join namespaces n on n.id = p.namespace_id
join organizations o on o.id = n.org_id
where o.slug = $1
  and n.slug = $2
  and p.name = $3
  and v.version = $4
for update
`

type GetVersionForUpdateParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type GetVersionForUpdateRow struct {
	ID           pgtype.UUID `json:"id"`
	PackageID    pgtype.UUID `json:"package_id"`
	Version      string      `json:"version"`
	Lifecycle    string      `json:"lifecycle"`
	Visibility   string      `json:"visibility"`
	ManifestJson []byte      `json:"manifest_json"`
	Digest       pgtype.Text `json:"digest"`
}

func (q *Queries) GetVersionForUpdate(ctx context.Context, arg GetVersionForUpdateParams) (GetVersionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVersionForUpdate,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i GetVersionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.ManifestJson,
		&i.Digest,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
insert into audit_events (id, org_id, namespace_id, package_id, package_version_id, actor_service_account, action, metadata_json, created_at)
select $1, p.org_id, p.namespace_id, p.id, $2, $3, $4, $5, now()
from packages p
where p.id = $6
`

type InsertAuditEventParams struct {
	ID                  pgtype.UUID `json:"id"`
	PackageVersionID    pgtype.UUID `json:"package_version_id"`
	ActorServiceAccount pgtype.Text `json:"actor_service_account"`
	Action              string      `json:"action"`
	MetadataJson        []byte      `json:"metadata_json"`
	PackageID           pgtype.UUID `json:"package_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.PackageVersionID,
		arg.ActorServiceAccount,
		arg.Action,
		arg.MetadataJson,
		arg.PackageID,
	)
	return err
}

const listArtifactMetadataForVersion = `-- name: ListArtifactMetadataForVersion :many
select path, type, blob_digest, size_bytes, coalesce(target_path, '') as target_path
from artifact_files
where package_version_id = $1
order by path
`

type ListArtifactMetadataForVersionRow struct {
	Path       string `json:"path"`
	Type       string `json:"type"`
	BlobDigest string `json:"blob_digest"`
	SizeBytes  int64  `json:"size_bytes"`
	TargetPath string `json:"target_path"`
}

func (q *Queries) ListArtifactMetadataForVersion(ctx context.Context, packageVersionID pgtype.UUID) ([]ListArtifactMetadataForVersionRow, error) {
	rows, err := q.db.Query(ctx, listArtifactMetadataForVersion, packageVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactMetadataForVersionRow{}
	for rows.Next() {
		var i ListArtifactMetadataForVersionRow
		if err := rows.Scan(
			&i.Path,
			&i.Type,
			&i.BlobDigest,
			&i.SizeBytes,
			&i.TargetPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishVersion = `-- name: PublishVersion :one
update package_versions
set lifecycle = 'published',
    digest = $1,
    updated_at = now(),
    published_at = now()
where id = $2
returning version, lifecycle, digest, published_at
`

type PublishVersionParams struct {
	Digest pgtype.Text `json:"digest"`
	ID     pgtype.UUID `json:"id"`
}

type PublishVersionRow struct {
	Version     string             `json:"version"`
	Lifecycle   string             `json:"lifecycle"`
	Digest      pgtype.Text        `json:"digest"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) PublishVersion(ctx context.Context, arg PublishVersionParams) (PublishVersionRow, error) {
	row := q.db.QueryRow(ctx, publishVersion, arg.Digest, arg.ID)
	var i PublishVersionRow
	err := row.Scan(
		&i.Version,
		&i.Lifecycle,
		&i.Digest,
		&i.PublishedAt,
	)
	return i, err
}

const resetUnpublishedVersionToDraft = `-- name: ResetUnpublishedVersionToDraft :one
with version_row as (
  select v.id
  from package_versions v
  join packages p on p.id = v.package_id
  join namespaces n on n.id = p.namespace_id
  join organizations o on o.id = n.org_id
  where o.slug = $1
    and n.slug = $2
    and p.name = $3
    and v.version = $4
    and v.lifecycle in ('draft', 'review')
), deleted_approvals as (
  delete from approvals
  where package_version_id in (select id from version_row)
), deleted_comments as (
  delete from review_comments
  where review_id in (select id from reviews where package_version_id in (select id from version_row))
), deleted_reviews as (
  delete from reviews
  where package_version_id in (select id from version_row)
)
update package_versions
set lifecycle = 'draft',
    digest = null,
    published_at = null,
    updated_at = now()
where id in (select id from version_row)
returning version, lifecycle, visibility, coalesce(digest, '') as digest,
          coalesce(to_char(created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as created_at,
          coalesce(to_char(updated_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as updated_at,
          coalesce(to_char(published_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text as published_at
`

type ResetUnpublishedVersionToDraftParams struct {
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
	Version     string `json:"version"`
}

type ResetUnpublishedVersionToDraftRow struct {
	Version     string `json:"version"`
	Lifecycle   string `json:"lifecycle"`
	Visibility  string `json:"visibility"`
	Digest      string `json:"digest"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	PublishedAt string `json:"published_at"`
}

func (q *Queries) ResetUnpublishedVersionToDraft(ctx context.Context, arg ResetUnpublishedVersionToDraftParams) (ResetUnpublishedVersionToDraftRow, error) {
	row := q.db.QueryRow(ctx, resetUnpublishedVersionToDraft,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
		arg.Version,
	)
	var i ResetUnpublishedVersionToDraftRow
	err := row.Scan(
		&i.Version,
		&i.Lifecycle,
		&i.Visibility,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePackageVisibility = `-- name: UpdatePackageVisibility :one
update packages
set visibility = $1,
    updated_at = now()
where id = (
  select p.id from packages p
  join namespaces n on n.id = p.namespace_id
  join organizations o on o.id = n.org_id
  where o.slug = $2
    and n.slug = $3
    and p.name = $4
)
returning id, namespace_id, name, display_name, description, visibility, lifecycle, created_at, updated_at
`

type UpdatePackageVisibilityParams struct {
	Visibility  string `json:"visibility"`
	Org         string `json:"org"`
	Namespace   string `json:"namespace"`
	PackageName string `json:"package_name"`
}

type UpdatePackageVisibilityRow struct {
	ID          pgtype.UUID        `json:"id"`
	NamespaceID pgtype.UUID        `json:"namespace_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	Lifecycle   string             `json:"lifecycle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePackageVisibility(ctx context.Context, arg UpdatePackageVisibilityParams) (UpdatePackageVisibilityRow, error) {
	row := q.db.QueryRow(ctx, updatePackageVisibility,
		arg.Visibility,
		arg.Org,
		arg.Namespace,
		arg.PackageName,
	)
	var i UpdatePackageVisibilityRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Visibility,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVersionManifest = `-- name: UpdateVersionManifest :exec
update package_versions
set manifest_json = $1,
    updated_at = now()
where id = $2
`

type UpdateVersionManifestParams struct {
	ManifestJson []byte      `json:"manifest_json"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVersionManifest(ctx context.Context, arg UpdateVersionManifestParams) error {
	_, err := q.db.Exec(ctx, updateVersionManifest, arg.ManifestJson, arg.ID)
	return err
}

const upsertArtifactBlob = `-- name: UpsertArtifactBlob :exec
insert into artifact_blobs (digest, content, size_bytes, created_at)
values ($1, $2, $3, now())
on conflict (digest) do nothing
`

type UpsertArtifactBlobParams struct {
	Digest    string `json:"digest"`
	Content   []byte `json:"content"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertArtifactBlob(ctx context.Context, arg UpsertArtifactBlobParams) error {
	_, err := q.db.Exec(ctx, upsertArtifactBlob, arg.Digest, arg.Content, arg.SizeBytes)
	return err
}

const upsertArtifactFile = `-- name: UpsertArtifactFile :one
insert into artifact_files (id, package_version_id, path, type, content_type, blob_digest, size_bytes, target_path, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, now())
on conflict (package_version_id, path) do update
set type = excluded.type,
    content_type = excluded.content_type,
    blob_digest = excluded.blob_digest,
    size_bytes = excluded.size_bytes,
    target_path = excluded.target_path
returning id, path, type, content_type, blob_digest, size_bytes, target_path, created_at
`

type UpsertArtifactFileParams struct {
	ID               pgtype.UUID `json:"id"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	Path             string      `json:"path"`
	Type             string      `json:"type"`
	ContentType      string      `json:"content_type"`
	BlobDigest       string      `json:"blob_digest"`
	SizeBytes        int64       `json:"size_bytes"`
	TargetPath       pgtype.Text `json:"target_path"`
}

type UpsertArtifactFileRow struct {
	ID          pgtype.UUID        `json:"id"`
	Path        string             `json:"path"`
	Type        string             `json:"type"`
	ContentType string             `json:"content_type"`
	BlobDigest  string             `json:"blob_digest"`
	SizeBytes   int64              `json:"size_bytes"`
	TargetPath  pgtype.Text        `json:"target_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertArtifactFile(ctx context.Context, arg UpsertArtifactFileParams) (UpsertArtifactFileRow, error) {
	row := q.db.QueryRow(ctx, upsertArtifactFile,
		arg.ID,
		arg.PackageVersionID,
		arg.Path,
		arg.Type,
		arg.ContentType,
		arg.BlobDigest,
		arg.SizeBytes,
		arg.TargetPath,
	)
	var i UpsertArtifactFileRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Type,
		&i.ContentType,
		&i.BlobDigest,
		&i.SizeBytes,
		&i.TargetPath,
		&i.CreatedAt,
	)
	return i, err
}

const upsertArtifactLocation = `-- name: UpsertArtifactLocation :exec
insert into artifact_locations (digest, storage_driver, storage_uri, created_at)
values ($1, 'postgres', null, now())
on conflict (digest) do nothing
`

func (q *Queries) UpsertArtifactLocation(ctx context.Context, digest string) error {
	_, err := q.db.Exec(ctx, upsertArtifactLocation, digest)
	return err
}

const upsertProjectArtifactInstall = `-- name: UpsertProjectArtifactInstall :exec
insert into project_artifact_installs (id, project_id, package_id, package_version_id, installed_digest, installed_at, last_checked_at, metadata_json)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  now(),
  now(),
  $6
)
on conflict (project_id, package_id) do update
set package_version_id = excluded.package_version_id,
    installed_digest = excluded.installed_digest,
    installed_at = excluded.installed_at,
    last_checked_at = now(),
    metadata_json = excluded.metadata_json
`

type UpsertProjectArtifactInstallParams struct {
	ID               pgtype.UUID `json:"id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	PackageID        pgtype.UUID `json:"package_id"`
	PackageVersionID pgtype.UUID `json:"package_version_id"`
	InstalledDigest  string      `json:"installed_digest"`
	MetadataJson     []byte      `json:"metadata_json"`
}

func (q *Queries) UpsertProjectArtifactInstall(ctx context.Context, arg UpsertProjectArtifactInstallParams) error {
	_, err := q.db.Exec(ctx, upsertProjectArtifactInstall,
		arg.ID,
		arg.ProjectID,
		arg.PackageID,
		arg.PackageVersionID,
		arg.InstalledDigest,
		arg.MetadataJson,
	)
	return err
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :exec
insert into package_search_documents (
  package_id,
  latest_published_version_id,
  search_text,
  labels_json,
  artifact_types,
  lifecycle,
  visibility,
  updated_at
)
values (
  $1,
  $2,
  to_tsvector('english', $3),
  $4,
  $5::text[],
  $6,
  $7,
  now()
)
on conflict (package_id) do update
set latest_published_version_id = excluded.latest_published_version_id,
    search_text = excluded.search_text,
    labels_json = excluded.labels_json,
    artifact_types = excluded.artifact_types,
    lifecycle = excluded.lifecycle,
    visibility = excluded.visibility,
    updated_at = excluded.updated_at
`

type UpsertSearchDocumentParams struct {
	PackageID                pgtype.UUID `json:"package_id"`
	LatestPublishedVersionID pgtype.UUID `json:"latest_published_version_id"`
	SearchText               []byte      `json:"search_text"`
	LabelsJson               []byte      `json:"labels_json"`
	ArtifactTypes            []string    `json:"artifact_types"`
	Lifecycle                string      `json:"lifecycle"`
	Visibility               string      `json:"visibility"`
}

func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertSearchDocument,
		arg.PackageID,
		arg.LatestPublishedVersionID,
		arg.SearchText,
		arg.LabelsJson,
		arg.ArtifactTypes,
		arg.Lifecycle,
		arg.Visibility,
	)
	return err
}

const yankVersion = `-- name: YankVersion :one
update package_versions
set lifecycle = 'yanked',
    updated_at = now()
where id = $1
  and lifecycle in ('published', 'deprecated')
returning version, lifecycle, updated_at
`

type YankVersionRow struct {
	Version   string             `json:"version"`
	Lifecycle string             `json:"lifecycle"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) YankVersion(ctx context.Context, id pgtype.UUID) (YankVersionRow, error) {
	row := q.db.QueryRow(ctx, yankVersion, id)
	var i YankVersionRow
	err := row.Scan(&i.Version, &i.Lifecycle, &i.UpdatedAt)
	return i, err
}
